### ISSUE TITLE
Foundations revisited

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#108]
https://formal-methods-mpi.github.io/Workshop.jl/stable/5_additional/extensive-foundations/

I have mixed feeling about this one because it appears as the first version of chapter 2 which was then decided to be made shorter for chapter 2.
A lot of the sentences are the same os it's a bit harder to see where the new information is. 
Perhaps boiled this one down to the new stuff only? though I can see some value in reestablishing a previous fact, perhaps there is way that only what is needed to mention the new fact can be reformulated here.

Also, I guess there is an argument to be made to have the definition of each type of object ot be included in chapter 2, e.g. variable, function, vector, etc. it was ok for me not to have them when reading chapter 2 because I knew these definitions, but if there are needed, it is most likely when these objects are introduced the first time? or did you think it be overwhelming and easier to have a vague idea and intuition and read the definitions later?

**Comment by Maximilian-Stefan-Ernst** [comment]
@MalikaIhle thanks for the suggestions... this chapter is indeed the longer version of chapter 2. I think for most participants it is fine to have the short version without definitions as the "main" chapter in the workshop, because we expect the participants to have previous programming experience in R - so they should know what a variable, function, vector etc. is. But we decided to keep the longer version in case someone feels overwhelmed.

@moritzketzer @aaronpeikert I think we should decide what to do here... 
I would suggest adding a link to the "extensive foundations" at the end of chapter 2, and maybe adding a disclaimer to "extensive foundations" that this is basically a longer version of ch. 2 in case this one was too fast?

@moritzketzer In any case, I would suggest reformulating "extensive foundations" a bit so there are no dublications of sentences / examples, because I guess this just feels dull for the participants.

What are your opinions on this?

**Comment by moritzketzer** [comment]
I agree, we wanted to leave this in case we have participants that are overwhelmed by the next chapters and would be stuck without anything to do.

I think we should make it explicit, that people should try the next chapters and only do the extensive version if they are stuck and the chapters exceed their skill level.

@aaronpeikert what do you think? Leave in, link at the end of chapter 2 and reword?

**Comment by aaronpeikert** [comment]
Yes, I would do all of the above:

- [ ] leave in
- [ ] reword (just ask our good old friend GPT)
- [ ] add disclaimer at beginning
- [ ] add link at end of Chapter 2

@moritzketzer please make a PR for this.

**Comment by moritzketzer** [comment]
I was wondering if it is better to leave what is identical without rephrasing, because it is easier to spot what a person already read, and if a person needs some basic training, redundancy and repetiton might also make learning easier for people who need it. if a person finds it too dull they should probably spend no time at all in the chapter?

**Comment by Maximilian-Stefan-Ernst** [comment]
Should be solved in PR #125, but for now we did not reword - we thought it may be okay now as we made it clear that this section is simply a longer version of the cheat sheet for participants that are completely overwhelmed by the normal workshop.
