### ISSUE TITLE
Formulate instructions for participants

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [formal-methods-mpi/Workshop.jl#114]
The e-mail to the previous workshop is [here](https://github.com/formal-methods-mpi/Workshop.jl/blob/main/mails/signup.md).

**Comment by MalikaIhle** [comment]
is this enough for you?

Instructions for all attendees
You need to have admin rights to your computer in order to install software:
* All attendees: please install R and RStudio: https://posit.co/download/rstudio-desktop/ 
* Attendees to the Julia workshop: please install Julia, VSCode and Julia extension for VSCode following these instructions: https://formal-methods-mpi.github.io/Workshop.jl/stable/0_preparation/preparation/ 
Other software (namely Git) will be installed during the workshops.
